package com.example.islami_project.ui.theme

import com.example.islami_project.ui.theme.Model.SuraDM

class Constants  {
    companion object{

        // Recommended: place this in a companion object, object, or top-level property
        val Suras: List<SuraDM> = listOf(
            SuraDM(1, "الفاتحة", "Al-Fatiha", 7),
            SuraDM(2, "البقرة", "Al-Baqarah", 286),
            SuraDM(3, "آل عمران", "Aal-E-Imran", 200),
            SuraDM(4, "النساء", "An-Nisa'", 176),
            SuraDM(5, "المائدة", "Al-Ma'idah", 120),
            SuraDM(6, "الأنعام", "Al-An'am", 165),
            SuraDM(7, "الأعراف", "Al-A'raf", 206),
            SuraDM(8, "الأنفال", "Al-Anfal", 75),
            SuraDM(9, "التوبة", "At-Tawbah", 129),
            SuraDM(10, "يونس", "Yunus", 109),
            SuraDM(11, "هود", "Hud", 123),
            SuraDM(12, "يوسف", "Yusuf", 111),
            SuraDM(13, "الرعد", "Ar-Ra'd", 43),
            SuraDM(14, "إبراهيم", "Ibrahim", 52),
            SuraDM(15, "الحجر", "Al-Hijr", 99),
            SuraDM(16, "النحل", "An-Nahl", 128),
            SuraDM(17, "الإسراء", "Al-Isra", 111),
            SuraDM(18, "الكهف", "Al-Kahf", 110),
            SuraDM(19, "مريم", "Maryam", 98),
            SuraDM(20, "طه", "Ta-Ha", 135),
            SuraDM(21, "الأنبياء", "Al-Anbiya", 112),
            SuraDM(22, "الحج", "Al-Hajj", 78),
            SuraDM(23, "المؤمنون", "Al-Mu'minun", 118),
            SuraDM(24, "النور", "An-Nur", 64),
            SuraDM(25, "الفرقان", "Al-Furqan", 77),
            SuraDM(26, "الشعراء", "Ash-Shu'ara", 227),
            SuraDM(27, "النمل", "An-Naml", 93),
            SuraDM(28, "القصص", "Al-Qasas", 88),
            SuraDM(29, "العنكبوت", "Al-Ankabut", 69),
            SuraDM(30, "الروم", "Ar-Rum", 60),
            SuraDM(31, "لقمان", "Luqman", 34),
            SuraDM(32, "السجدة", "As-Sajda", 30),
            SuraDM(33, "الأحزاب", "Al-Ahzab", 73),
            SuraDM(34, "سبأ", "Saba", 54),
            SuraDM(35, "فاطر", "Fatir", 45),
            SuraDM(36, "يس", "Ya-Sin", 83),
            SuraDM(37, "الصافات", "As-Saffat", 182),
            SuraDM(38, "ص", "Sad", 88),
            SuraDM(39, "الزمر", "Az-Zumar", 75),
            SuraDM(40, "غافر", "Ghafir", 85),
            SuraDM(41, "فصلت", "Fussilat", 54),
            SuraDM(42, "الشورى", "Ash-Shura", 53),
            SuraDM(43, "الزخرف", "Az-Zukhruf", 89),
            SuraDM(44, "الدخان", "Ad-Dukhan", 59),
            SuraDM(45, "الجاثية", "Al-Jathiya", 37),
            SuraDM(46, "الأحقاف", "Al-Ahqaf", 35),
            SuraDM(47, "محمد", "Muhammad", 38),
            SuraDM(48, "الفتح", "Al-Fath", 29),
            SuraDM(49, "الحجرات", "Al-Hujurat", 18),
            SuraDM(50, "ق", "Qaf", 45),
            SuraDM(51, "الذاريات", "Adh-Dhariyat", 60),
            SuraDM(52, "الطور", "At-Tur", 49),
            SuraDM(53, "النجم", "An-Najm", 62),
            SuraDM(54, "القمر", "Al-Qamar", 55),
            SuraDM(55, "الرحمن", "Ar-Rahman", 78),
            SuraDM(56, "الواقعة", "Al-Waqi'a", 96),
            SuraDM(57, "الحديد", "Al-Hadid", 29),
            SuraDM(58, "المجادلة", "Al-Mujadila", 22),
            SuraDM(59, "الحشر", "Al-Hashr", 24),
            SuraDM(60, "الممتحنة", "Al-Mumtahina", 13),
            SuraDM(61, "الصف", "As-Saff", 14),
            SuraDM(62, "الجمعة", "Al-Jumu'a", 11),
            SuraDM(63, "المنافقون", "Al-Munafiqun", 11),
            SuraDM(64, "التغابن", "At-Taghabun", 18),
            SuraDM(65, "الطلاق", "At-Talaq", 12),
            SuraDM(66, "التحريم", "At-Tahrim", 12),
            SuraDM(67, "الملك", "Al-Mulk", 30),
            SuraDM(68, "القلم", "Al-Qalam", 52),
            SuraDM(69, "الحاقة", "Al-Haqqah", 52),
            SuraDM(70, "المعارج", "Al-Ma'arij", 44),
            SuraDM(71, "نوح", "Nuh", 28),
            SuraDM(72, "الجن", "Al-Jinn", 28),
            SuraDM(73, "المزمل", "Al-Muzzammil", 20),
            SuraDM(74, "المدثر", "Al-Muddathir", 56),
            SuraDM(75, "القيامة", "Al-Qiyamah", 40),
            SuraDM(76, "الإنسان", "Al-Insan", 31),
            SuraDM(77, "المرسلات", "Al-Mursalat", 50),
            SuraDM(78, "النبأ", "An-Naba'", 40),
            SuraDM(79, "النازعات", "An-Nazi'at", 46),
            SuraDM(80, "عبس", "Abasa", 42),
            SuraDM(81, "التكوير", "At-Takwir", 29),
            SuraDM(82, "الإنفطار", "Al-Infitar", 19),
            SuraDM(83, "المطففين", "Al-Mutaffifin", 36),
            SuraDM(84, "الإنشقاق", "Al-Inshiqaq", 25),
            SuraDM(85, "البروج", "Al-Buruj", 22),
            SuraDM(86, "الطارق", "At-Tariq", 17),
            SuraDM(87, "الأعلى", "Al-A'la", 19),
            SuraDM(88, "الغاشية", "Al-Ghashiyah", 26),
            SuraDM(89, "الفجر", "Al-Fajr", 30),
            SuraDM(90, "البلد", "Al-Balad", 20),
            SuraDM(91, "الشمس", "Ash-Shams", 15),
            SuraDM(92, "الليل", "Al-Lail", 21),
            SuraDM(93, "الضحى", "Ad-Duha", 11),
            SuraDM(94, "الشرح", "Ash-Sharh", 8),
            SuraDM(95, "التين", "At-Tin", 8),
            SuraDM(96, "العلق", "Al-Alaq", 19),
            SuraDM(97, "القدر", "Al-Qadr", 5),
            SuraDM(98, "البينة", "Al-Bayyina", 8),
            SuraDM(99, "الزلزلة", "Az-Zalzalah", 8),
            SuraDM(100, "العاديات", "Al-Adiyat", 11),
            SuraDM(101, "القارعة", "Al-Qari'a", 11),
            SuraDM(102, "التكاثر", "At-Takathur", 8),
            SuraDM(103, "العصر", "Al-Asr", 3),
            SuraDM(104, "الهمزة", "Al-Humazah", 9),
            SuraDM(105, "الفيل", "Al-Fil", 5),
            SuraDM(106, "قريش", "Quraysh", 4),
            SuraDM(107, "الماعون", "Al-Ma'un", 7),
            SuraDM(108, "الكوثر", "Al-Kawthar", 3),
            SuraDM(109, "الكافرون", "Al-Kafirun", 6),
            SuraDM(110, "النصر", "An-Nasr", 3),
            SuraDM(111, "المسد", "Al-Masad", 5),
            SuraDM(112, "الإخلاص", "Al-Ikhlas", 4),
            SuraDM(113, "الفلق", "Al-Falaq", 5),
            SuraDM(114, "الناس", "An-Nas", 6)
        )
    }
}
